//This script does not seem to be preloaded in BrowserViews
console.log('preload.js 0');//not running...
alert('preload.js 0');//not running...
require('fs');//example nodejs function that should run if node is available.
